name: nucseqret
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastqc
  - trimmomatic
  - bowtie2
  - samtools
  - macs3
  - bedtools
  - deeptools
  - ucsc-liftover
  - sra-tools
  - biopython
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ucsc-bedgraphtobigwig
  - scipy
  - brokenaxes
  - numba
  - tqdm
  - scikit-learn
  - statsmodels
  - fastp
  - pip:
      - pipdeptree
      - multiqc