name: nucseqret
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - biopython
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - numba
  - tqdm
  - scikit-learn
  - statsmodels
  - fastp
  - pybedtools
  - pyfaidx
  - seqkit
  - psutil
  - brokenaxes
  - miller
  - polars
  - pyarrow
  - dask
  - datashader
  - pip:
      - pipdeptree
      - line_profiler